### ISSUE TITLE
下载shadowsocksR-4.7.0-win.7z，windows defender报毒：特洛伊木马

### ISSUE THREAD

**Issue by newamber** [shadowsocksr-backup/shadowsocksr-csharp#4]
刚开始看岔了，改回来了，如题

WD提示：
Trojan:Win32/Vigorf.A

**Comment by Satanepigone** [comment]
下ssr的4.7.0吧，新版用着多好 

    LoveOnePing <notifications@github.com> 于 2018年3月3日, 星期六, 上午 12:14 写道：
 

 如题—

**Comment by notlixiang** [comment]
我的也报毒，不敢用

**Comment by ghost** [comment]
This is non-supported software. No one will investigate issues.

Where did you download ShadowsocksR-4.7.0-win.7z from?

Check that ShadowsocksR-4.7.0-win.7z has file size 715,587 bytes and SHA256 sum 481a20d24e0e0f4d8b4a872cd82650a7a2721e699416bc0a43351cffd1b27fa6.

Check extracted exe file with Microsoft Safety Scanner msert.exe from https://www.microsoft.com/en-us/wdsi/products/scanner

Check extracted exe file with Malwarebytes from https://www.malwarebytes.com

**Comment by WHBLeer** [comment]
大可放心用  我用了快半年了

**Comment by lza945** [comment]
我的ShadowsocksR一直连接我的vps超时，为啥
