### ISSUE TITLE
Windows 10 声音卡顿

### ISSUE THREAD

**Issue by V-zhangyunxiang** [shadowsocksr-backup/shadowsocksr-csharp#5]
一直都有电脑用着用着音频和视频的声音突然卡顿，排查了很多因素，发现是 SSR 客户端 PAC 的问题，具体什么原因尚不得知，但退出 SS 客户端后声音恢复正常，以下是参数信息
SSR 版本： ShadowsocksR-4.7.0-win
Window10 版本：1803 17134.1 ，不是 17134.1 也有卡顿
加密：aes-256-cfb
协议：auth_sha1_v4
混淆：http_simple
端口：443
硅谷节点
兼容 SS
烦请作者能否查找一下原因，如需要更多信息，麻烦回复我，谢谢。

**Comment by pythonEdge** [comment]
最好再提供一下声卡和声卡驱动相关的信息
