### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by jiaohonggang** [shadowsocksr-backup/shadowsocksr-csharp#9]
1

**Comment by Alan0j** [comment]
`[2019-07-10 18:50:21] [Info] Direct connect www.google.com:443
[2019-07-10 18:50:22] [Error] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。 127.0.0.1:443
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)`
![image](https://user-images.githubusercontent.com/46082634/60963566-bbc69200-a343-11e9-8106-c7643780e317.png)
